[workspace]
members = [
    "./chapter02_value_object/",
    "./chapter03_entity/",
    "./chapter04_domain_service/",
    "./chapter05_repository/",
    "./chapter06_application_service/",
    "./chapter08_sample_application/",
]
